# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_USER: ROLE_USER
        ROLE_ADMIN:           [ROLE_ADMIN, ROLE_DIRECTIONFR, ROLE_AGENTTFR]
        ROLE_SUPER_ADMIN: [ ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            form_login:
                provider:    fos_userbundle
                csrf_provider: form.csrf_provider
                login_path: /login
                use_forward: false
                check_path: /login_check
                failure_path: null
                success_handler: redirect.after.login
            logout:
                path: /logout
                target: /
                success_handler: redirect.after.logout
            anonymous:    true
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER }


