<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MeetRepository extends EntityRepository
{

    public function getCustomerByDateHourTreatement($date)
    {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('u.id')
            ->from('AppBundle:User','u')
            ->join('AppBundle:Meet','m')
            ->where('m.cmkSfieldfHTreatment LIKE :date AND u.id = m.customerId')
            ->setParameter('date', '%"'.$date.'"%');
        return $qb->getQuery()->getResult();
    }
    
    public function getMeetWithDoublant(){
        $meets=$this->findAll();
         $meetDoublant=array();
        foreach($meets as $meet){
            foreach ($meetDoublant as $md){
              if($md["nom"]==$meet->getNom()&&$md["prenom"]==$meet->getSurname()){
                 // var_dump($meet);die;
                  $meet->setIsDouble(true);
                  $md["store"]->setIsDouble(true);
              }  
            }
            $meetDoublant[]=array("nom"=>$meet->getNom(),"prenom"=>$meet->getSurname(),"store"=>$meet);
        
        }
       return $meets; 
    }

}
